# Setup
name:         "Blackbox Thinking"
title:        "Blackbox Thinking"
locale:       "en"

description:  "Mastering technology. Not a slave to it."
logo: "https://s3.eu-west-2.amazonaws.com/assets.blackboxthinking.com/images/bbox-logo-web.png"

# Gems
plugins:
  - jekyll-seo-tag


defaults:
  -
    scope:
      path: ""
    values:
      image: "https://s3.eu-west-2.amazonaws.com/assets.blackboxthinking.com/images/bbox-logo-web.png"

#Others
markdown: kramdown

# Set the URL format
permalink: none

collections:
  authors:
    output: true
    permalink: /:collection/:name

# Site Settings
url: "https://www.blackboxthinking.com/"
img_root: "https://s3.eu-west-2.amazonaws.com/assets.blackboxthinking.com/images"

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

# Social media
twitter:
  username: abid_khairul
  card: summary

facebook:
  publisher: https://www.facebook.com/bboxthinking/

social:
  name: Blackbox Thinking
  links:
    - https://twitter.com/abid_khairul
    - https://www.facebook.com/bboxthinking/
    - https://www.linkedin.com/company/blackbox-thinking/
    - https://github.com/blackbox-thinking/

# google_site_verification: xxxxx

