# Setup
name:         Blackbox Thinking
title:        Blackbox Thinking
locale:       "en"

# Gems
plugins:
  - jekyll-avatar

#Others
markdown: kramdown

# Set the URL format
permalink: none

collections:
  authors:
    output: true
    permalink: /:collection/:name


# Site Settings
url: "http://localhost:4000"

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

